apiVersion: v1
kind: Pod
metadata:
  name: central-waitpod
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  containers:
    - name: curl-gitea
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      command:
        - /bin/bash
        - -c
        - |
          echo -n "Waiting for ACS Central service\n"
          until [ $(curl -s -k -o /dev/null -w "%{http_code}" https://central) -eq 200 ]; do echo -n "."; sleep 15; done
          echo -e "Online!\n"
  restartPolicy: Never
