apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: acs-init-bundle
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.7
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/pull
              echo ""
              echo "========================"
              yum install -qy jq
              CENTRAL=$(oc get svc central -n stackrox -o jsonpath='{.spec.clusterIP}')
              echo $CENTRAL
              INIT_BUNDLE=$(curl -X POST -k -H 'Authorization: Basic YWRtaW46c3RhY2tyb3g=' https://$CENTRAL/v1/cluster-init/init-bundles --data '{"name": "production5"}')
              echo $INIT_BUNDLE | jq -r .kubectlBundle | base64 -d > init-bundle.yaml
              oc apply -f init-bundle.yaml
              echo "========================"
          imagePullPolicy: Always
          name: acs-init-task
          env:
          - name: ACS_PASSWORD
            value: "stackrox"
      restartPolicy: OnFailure
      serviceAccount: acs-gitops
      serviceAccountName: acs-gitops
      terminationGracePeriodSeconds: 30

