apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
  - 1.ns.yaml
  - 2.subs.yaml
  - 3.rbac.yaml
  - 4.password.yaml
  - 5.central.yaml
  - 6.init-bundle.yaml
  - 7.securedcluster.yaml

