apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: openshift-gitops
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: Git
  pathname: https://github.com/rcarrata/acs-gitops
