apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-argo-app
  namespace: openshift-gitops
  labels:
    app: acs-argo-app
spec:
  clusterSelector:
    matchExpressions:
      - key: usage
        operator: In
        values:
          - production
