apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acs-argo-app
  namespace: openshift-gitops
  labels:
    app: acs-argo-app
  annotations:
    apps.open-cluster-management.io/github-path: acs-deploy/applications
    apps.open-cluster-management.io/github-branch: develop
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: openshift-gitops/gitops
  placement:
    placementRef:
      name: acs-argo-app
      kind: PlacementRule
      group: apps.open-cluster-management.io
