apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-security
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/rcarrata/acs-gitops
      revision: develop
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rcarrata/acs-gitops
        targetRevision: develop
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
