apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acs-argo-app
  namespace: application-samples
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - acs-argo-app
